---
- hosts: localhost
  gather_facts: true

  tasks:
   - name: Get list of Helm repositories
     command: helm repo list -o json
     register: helm_repos
     changed_when: false

   - name: Ensure Cilium repo is added
     kubernetes.core.helm_repository:
       name: cilium
       repo_url: https://helm.cilium.io
     when: "'cilium' not in (helm_repos.stdout | from_json | map(attribute='name'))"

   - name: Deploy Tetragon
     kubernetes.core.helm:
       name: tetragon
       chart_ref: cilium/tetragon
       release_namespace: kube-system
       update_repo_cache: yes
       values:
         # Enable necessary kernel features for your lab nodes
         tetragon:
           enableBTF: true
           enableProcessCred: true
           enableProcessNs: true
           enableKernelEvents: true
           enableTracingPolicies: true
     when:
       - ansible_os_family == "Darwin"
       - "'tetragon' not in (helm_repos.stdout | from_json | map(attribute='name'))"

   - name: Install gateway api CRDs
     kubernetes.core.k8s:
       state: present
       namespace: kube-system
       src: yaml_files/gatewayapi_crds.yaml
       server_side_apply:
         field_manager: "ansible-manager"
         force_conflicts: true
     when: ansible_os_family == "Darwin"

   - name: Deploy Cilium chart and enable tetragon and hubble
     kubernetes.core.helm:
       name: cilium
       chart_ref: cilium/cilium
       release_namespace: kube-system
       update_repo_cache: yes
       values:
         # These tell Cilium to replace kube-proxy
         kubeProxyReplacement: true
         k8sServiceHost: "kind-control-plane"
         k8sServicePort: "6443"
         l2announcements:
           enabled: true
         devices:
           - eth0
         ipam:
           mode: kubernetes
         gatewayAPI:
           enabled: true
         operator:
           replicas: 1
           # Enable Tetragon if you are using it
         tetragon:
           enabled: true
          # Useful for debugging/home labs
         hubble:
           relay:
             enabled: true
           ui:
             enabled: true
     when: ansible_os_family == "Darwin"

   - name: Deploy gateway api
     kubernetes.core.k8s:
       state: present
       src: yaml_files/gateway_api.yaml
     when: ansible_os_family == "Darwin"
