---
- name: Manage Local Cluster Policies
  hosts: localhost
  gather_facts: false

  tasks:
   - name: Ensure Kyverno Test Policy is applied
     kubernetes.core.k8s:
       state: present
       definition: "{{ lookup('file', 'test-policy.yaml') | from_yaml }}"
