---
- hosts: localhost
  gather_facts: true

  tasks:
   - name: Install helm in mac if not installed
     ansible.builtin.debug:
       msg: "Install helm by brew install helm"
     when: ansible_os_family == "Darwin"

   - name: Deploy Kind cluster on Mac
     ansible.builtin.command: "kind create cluster --name kind --config yaml_files/kind.yaml"
     register: kind_result
     changed_when: "'Creating cluster' in kind_result.stdout"
     failed_when:
       - kind_result.rc != 0
       - "'already exists' not in kind_result.stderr"
     when: ansible_os_family == "Darwin"
